version: '3'

networks:
  http-proxy:

volumes:
  traefik-acme:
  shaarli-cache:
  shaarli-data:

services:
  shaarli:
    image: shaarli/shaarli:latest
    build: ./
    networks:
      - http-proxy
    volumes:
      - shaarli-cache:/var/www/shaarli/cache
      - shaarli-data:/var/www/shaarli/data
    labels:
      traefik.domain: "localhost"
      traefik.backend: shaarli
      traefik.frontend.rule: "Host:localhost"

  traefik:
    image: traefik:1.7-alpine
    command:
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::81 TLS"
      - "--retry"
      - "--docker"
      - "--docker.domain=localhost"
      - "--docker.exposedbydefault=true"
      - "--docker.watch=true"
      - "--acme"
      - "--acme.domains=localhost"
      - "--acme.email=zero@zero.org"
      - "--acme.entrypoint=https"
      - "--acme.onhostrule=true"
      - "--acme.storage=/acme/acme.json"
      - "--acme.httpchallenge"
      - "--acme.httpchallenge.entrypoint=http"
    networks:
      - http-proxy
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/acme
      
  cyberchef:
    image: mpepping/cyberchef
    ports:
      - "82:8000"
  
  openwebspider:
    image: pantyusha/openwebspider
    ports:
      - "83:9999"
      
  spiderfoot:
    build:
       context: ./spiderfoot
    image: spiderfoot
    container_name: spiderfoot
    ports:
      - "84:5001"
    restart: unless-stopped



#  postgres:
#    restart: on-failure:10
#    image: postgres
#    expose:
#      - "5432"
#    environment:
#      - POSTGRES_DB=intriguedb
#    volumes:
#      - "db-data:/var/lib/postgresql/data"

  # redis:
  #   image: redis
  #   expose:
  #     - "6379"

###########

#  intrigue-web:
#    build: https://github.com/intrigueio/intrigue-core.git
#    ports:
#      - "83:7777"
#    links:
#      - redis
#      - postgres
#    environment:
#      - INTRIGUE_ENV=docker
#      - REDIS_URI=redis://redis:6379/

#TO TEST
#  intrigue:
#    build:
#      context: ./intrigue
#    ports:
#      - "83:7777"

#relies on dokuwiki
#  ivre:

# 1 GB
  # dashboard:
  #    build:
  #      context: ./pereval-dash
  #    ports:
  #      - "86:80"

# checked
#   cyberchef:
#     image: mpepping/cyberchef
#     ports:
#       - "82:8000"
#
# # checked
#   openwebspider:
#     image: pantyusha/openwebspider
#     ports:
#       - "81:9999"
#
# # checked
#   spiderfoot:
#     build: https://github.com/smicallef/spiderfoot.git#v2.12.0-final
#     ports:
#       - "85:5001" # changed this after looking at documentation

# http://localhost:84/wisemapping/c/login
#  wisemapping:
#    image: wisemapping/webapp
#    ports:
#      - "84:8080"
#
# checked, works after a while
#  etherpad:
#    build:
#      context: ./etherpad-lite
#    ports:
#      - "89:9001"

# checked
 #TODO: check where docs lie; study redis
#   ethercalc:
#     image: audreyt/ethercalc
#     ports:
#       - "90:8000" #doesnt override anything!
#     links:
#       - redis

# checked
#  shaarli:
#    image: shaarli/shaarli
#    ports:
#      - "91:80"

# fails
#  xwiki:
#    image: xwiki
#    ports:
#      - "94:80"
#   xwiki:
#     image: "xwiki:lts-postgres-tomcat"
#     container_name: xwiki-postgres-tomcat-web
#     depends_on:
#       - db
#     ports:
#       - "94:8080"
#     environment:
#       - DB_USER=xwiki
#       - DB_PASSWORD=xwiki
#       - DB_HOST=xwiki-postgres-db
#     volumes:
#       - xwiki-data:/usr/local/xwiki
#     networks:
#       - bridge
#   db:
#     image: "postgres:9.5"
#     container_name: xwiki-postgres-db
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_ROOT_PASSWORD=xwiki
#       - POSTGRES_PASSWORD=xwiki
#       - POSTGRES_USER=xwiki
#       - POSTGRES_DB=xwiki
#       - POSTGRES_INITDB_ARGS="--encoding=UTF8"
#     networks:
#       - bridge
# volumes:
#   postgres-data: {}
#   xwiki-data: {}

#
#  hackpad:
#    build: https://github.com/dropbox/hackpad.git#da0b3dbc3525cd3094c52975d11817ab30087ac9
#    ports:
#      - "92:9000"
#
# /app/docker-runner.sh: line 16: mysqladmin: command not found
#  paperwork:
#    image: conoria/paperwork
#    ports:
#      - "93:80"
#
#volumes:
# db-data:
